FROM python:3.12-slim

WORKDIR /app

RUN apt-get update \
 && apt-get upgrade -y \
 && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir redis==5.2.0

COPY services/worker/ ./

CMD ["python", "worker.py"]
